name = "AdventOfCode2018"
uuid = "2a2b9ce1-37a6-412f-b004-f1678a056eed"
authors = ["Alexander Seiler <seileralex@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
